version: "3.9"
networks:
  default:
    name: "mattermost-apps-dev"
services:
  mattermost-apps-golang-hello-world:
    image: "golang:latest"
    restart: "unless-stopped"
    working_dir: "/app"
    ports:
      - "4000:4000"
    environment:
      MATTERMOST_SITEURL: "http://mattermost:8065"
      APP_HOST: "mattermost-apps-golang-hello-world" # Same as the service's network name
      APP_PORT: 4000
    volumes:
      - "./:/app"
    command: "bash -c 'go run .'"
