version: "3.9"
networks:
  default:
    name: "mattermost-apps-dev"
services:
  mattermost-apps-python-hello-world:
    image: "python:latest"
    restart: "unless-stopped"
    working_dir: "/app"
    ports:
      - "8090:8090"
    environment:
      MATTERMOST_SITEURL: "http://mattermost:8065"
      APP_HOST: "mattermost-apps-python-hello-world" # Same as the service's network name
      APP_PORT: 8090
    volumes:
      - "./:/app"
      - "../mattermost_models/:/app/src/mattermost_models"
    command: "bash -c 'pip3 install -r requirements.txt -q && cd src && python3 dynamic-hello-world.py'"
